// <auto-generated />
using System;
using ChatApp.DAL.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ChatApp.DAL.Migrations
{
    [DbContext(typeof(ChatAppContext))]
    [Migration("20231024183924_ReadMessages")]
    partial class ReadMessages
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ChatApp.DAL.Entities.Chat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Chats");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2023, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2023, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2023, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2023, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2023, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2023, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2023, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2023, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2023, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2023, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2023, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2023, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2023, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2023, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2023, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2023, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2023, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2023, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2023, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2023, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 21,
                            CreatedAt = new DateTime(2023, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 22,
                            CreatedAt = new DateTime(2023, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 23,
                            CreatedAt = new DateTime(2023, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 24,
                            CreatedAt = new DateTime(2023, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 25,
                            CreatedAt = new DateTime(2023, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 26,
                            CreatedAt = new DateTime(2023, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 27,
                            CreatedAt = new DateTime(2023, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 28,
                            CreatedAt = new DateTime(2023, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 29,
                            CreatedAt = new DateTime(2023, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 30,
                            CreatedAt = new DateTime(2023, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 31,
                            CreatedAt = new DateTime(2023, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 32,
                            CreatedAt = new DateTime(2023, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 33,
                            CreatedAt = new DateTime(2023, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 34,
                            CreatedAt = new DateTime(2023, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 35,
                            CreatedAt = new DateTime(2023, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 36,
                            CreatedAt = new DateTime(2023, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 37,
                            CreatedAt = new DateTime(2023, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 38,
                            CreatedAt = new DateTime(2023, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 39,
                            CreatedAt = new DateTime(2023, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 40,
                            CreatedAt = new DateTime(2023, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("ChatApp.DAL.Entities.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ChatId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("ChatId");

                    b.HasIndex("UserId");

                    b.ToTable("Messages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ChatId = 26,
                            CreatedAt = new DateTime(2023, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRead = true,
                            UserId = 31,
                            Value = "Laudantium dignissimos ut expedita quasi necessitatibus facilis illo vitae consequuntur."
                        },
                        new
                        {
                            Id = 2,
                            ChatId = 36,
                            CreatedAt = new DateTime(2023, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRead = true,
                            UserId = 6,
                            Value = "Et quam nulla vel quae omnis."
                        },
                        new
                        {
                            Id = 3,
                            ChatId = 14,
                            CreatedAt = new DateTime(2023, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRead = true,
                            UserId = 34,
                            Value = "Modi repellendus repellendus sequi aut quibusdam ullam molestiae possimus."
                        },
                        new
                        {
                            Id = 4,
                            ChatId = 38,
                            CreatedAt = new DateTime(2023, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRead = true,
                            UserId = 28,
                            Value = "In quos autem deleniti consequatur facilis mollitia natus."
                        },
                        new
                        {
                            Id = 5,
                            ChatId = 35,
                            CreatedAt = new DateTime(2023, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRead = true,
                            UserId = 34,
                            Value = "Ullam exercitationem repudiandae."
                        },
                        new
                        {
                            Id = 6,
                            ChatId = 35,
                            CreatedAt = new DateTime(2023, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRead = true,
                            UserId = 23,
                            Value = "Quis blanditiis et perferendis est modi."
                        },
                        new
                        {
                            Id = 7,
                            ChatId = 14,
                            CreatedAt = new DateTime(2023, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRead = true,
                            UserId = 19,
                            Value = "Dolor nulla possimus expedita consequatur molestiae enim repellendus architecto non."
                        },
                        new
                        {
                            Id = 8,
                            ChatId = 12,
                            CreatedAt = new DateTime(2023, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRead = true,
                            UserId = 7,
                            Value = "Dolores omnis quia."
                        },
                        new
                        {
                            Id = 9,
                            ChatId = 26,
                            CreatedAt = new DateTime(2023, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRead = true,
                            UserId = 29,
                            Value = "Atque eos adipisci tenetur et ab iure iure."
                        },
                        new
                        {
                            Id = 10,
                            ChatId = 21,
                            CreatedAt = new DateTime(2023, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRead = true,
                            UserId = 40,
                            Value = "Ut consequatur id explicabo et placeat aut accusantium sunt adipisci."
                        },
                        new
                        {
                            Id = 11,
                            ChatId = 16,
                            CreatedAt = new DateTime(2023, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRead = true,
                            UserId = 37,
                            Value = "Repudiandae in ipsa sit quia architecto est iusto rerum."
                        },
                        new
                        {
                            Id = 12,
                            ChatId = 40,
                            CreatedAt = new DateTime(2023, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRead = true,
                            UserId = 25,
                            Value = "Qui saepe quia."
                        },
                        new
                        {
                            Id = 13,
                            ChatId = 33,
                            CreatedAt = new DateTime(2023, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRead = true,
                            UserId = 11,
                            Value = "Id eos odit distinctio expedita qui rerum."
                        },
                        new
                        {
                            Id = 14,
                            ChatId = 1,
                            CreatedAt = new DateTime(2023, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRead = true,
                            UserId = 2,
                            Value = "Ratione nihil laudantium quos aliquid ex eaque."
                        },
                        new
                        {
                            Id = 15,
                            ChatId = 13,
                            CreatedAt = new DateTime(2023, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRead = true,
                            UserId = 22,
                            Value = "Et harum a."
                        },
                        new
                        {
                            Id = 16,
                            ChatId = 11,
                            CreatedAt = new DateTime(2023, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRead = true,
                            UserId = 30,
                            Value = "Numquam ipsa veniam vero deleniti quam deserunt distinctio iure quis."
                        },
                        new
                        {
                            Id = 17,
                            ChatId = 29,
                            CreatedAt = new DateTime(2023, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRead = true,
                            UserId = 36,
                            Value = "Enim iure illo enim ipsum quis labore odio."
                        },
                        new
                        {
                            Id = 18,
                            ChatId = 39,
                            CreatedAt = new DateTime(2023, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRead = true,
                            UserId = 19,
                            Value = "At nostrum animi non."
                        },
                        new
                        {
                            Id = 19,
                            ChatId = 40,
                            CreatedAt = new DateTime(2023, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRead = true,
                            UserId = 37,
                            Value = "Similique laboriosam placeat sint."
                        },
                        new
                        {
                            Id = 20,
                            ChatId = 1,
                            CreatedAt = new DateTime(2023, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRead = true,
                            UserId = 27,
                            Value = "Eaque est fugit aut odit reiciendis fuga repellendus exercitationem optio."
                        },
                        new
                        {
                            Id = 21,
                            ChatId = 3,
                            CreatedAt = new DateTime(2023, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRead = true,
                            UserId = 14,
                            Value = "Repellendus magnam vitae totam voluptatem."
                        },
                        new
                        {
                            Id = 22,
                            ChatId = 17,
                            CreatedAt = new DateTime(2023, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRead = true,
                            UserId = 8,
                            Value = "Consectetur qui distinctio."
                        },
                        new
                        {
                            Id = 23,
                            ChatId = 3,
                            CreatedAt = new DateTime(2023, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRead = true,
                            UserId = 20,
                            Value = "Neque repudiandae doloribus autem."
                        },
                        new
                        {
                            Id = 24,
                            ChatId = 25,
                            CreatedAt = new DateTime(2023, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRead = true,
                            UserId = 29,
                            Value = "Magni natus consequuntur harum autem."
                        },
                        new
                        {
                            Id = 25,
                            ChatId = 25,
                            CreatedAt = new DateTime(2023, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRead = true,
                            UserId = 19,
                            Value = "Asperiores ut voluptatem."
                        },
                        new
                        {
                            Id = 26,
                            ChatId = 34,
                            CreatedAt = new DateTime(2023, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRead = true,
                            UserId = 38,
                            Value = "Voluptatem aliquam minima velit error non."
                        },
                        new
                        {
                            Id = 27,
                            ChatId = 27,
                            CreatedAt = new DateTime(2023, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRead = true,
                            UserId = 2,
                            Value = "Qui et est repellendus praesentium accusamus corporis et sit earum."
                        },
                        new
                        {
                            Id = 28,
                            ChatId = 30,
                            CreatedAt = new DateTime(2023, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRead = true,
                            UserId = 16,
                            Value = "A quo cupiditate et qui non adipisci et."
                        },
                        new
                        {
                            Id = 29,
                            ChatId = 27,
                            CreatedAt = new DateTime(2023, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRead = true,
                            UserId = 27,
                            Value = "Quibusdam voluptas distinctio impedit mollitia sint eos quis veniam."
                        },
                        new
                        {
                            Id = 30,
                            ChatId = 28,
                            CreatedAt = new DateTime(2023, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRead = true,
                            UserId = 9,
                            Value = "Aut itaque qui."
                        },
                        new
                        {
                            Id = 31,
                            ChatId = 27,
                            CreatedAt = new DateTime(2023, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRead = true,
                            UserId = 1,
                            Value = "Beatae occaecati natus id harum ullam dignissimos tempore hic deleniti."
                        },
                        new
                        {
                            Id = 32,
                            ChatId = 15,
                            CreatedAt = new DateTime(2023, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRead = true,
                            UserId = 27,
                            Value = "Illo rerum officiis doloribus et non deserunt nemo ut et."
                        },
                        new
                        {
                            Id = 33,
                            ChatId = 13,
                            CreatedAt = new DateTime(2023, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRead = true,
                            UserId = 28,
                            Value = "Veniam qui nihil."
                        },
                        new
                        {
                            Id = 34,
                            ChatId = 37,
                            CreatedAt = new DateTime(2023, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRead = true,
                            UserId = 11,
                            Value = "Quas molestiae voluptatem quia magnam inventore non ea."
                        },
                        new
                        {
                            Id = 35,
                            ChatId = 28,
                            CreatedAt = new DateTime(2023, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRead = true,
                            UserId = 4,
                            Value = "Distinctio ex et cum dolorum magni incidunt rerum non doloribus."
                        },
                        new
                        {
                            Id = 36,
                            ChatId = 6,
                            CreatedAt = new DateTime(2023, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRead = true,
                            UserId = 12,
                            Value = "Porro saepe commodi animi perferendis fuga magnam ut ipsum."
                        },
                        new
                        {
                            Id = 37,
                            ChatId = 17,
                            CreatedAt = new DateTime(2023, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRead = true,
                            UserId = 38,
                            Value = "Id cum dolorum."
                        },
                        new
                        {
                            Id = 38,
                            ChatId = 30,
                            CreatedAt = new DateTime(2023, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRead = true,
                            UserId = 8,
                            Value = "Voluptas iure ullam qui ipsam maxime ex nam est."
                        },
                        new
                        {
                            Id = 39,
                            ChatId = 27,
                            CreatedAt = new DateTime(2023, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRead = true,
                            UserId = 26,
                            Value = "Quod ea ut molestias quos ea optio est nisi."
                        },
                        new
                        {
                            Id = 40,
                            ChatId = 6,
                            CreatedAt = new DateTime(2023, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRead = true,
                            UserId = 5,
                            Value = "Corrupti quasi deleniti et aut qui est perferendis."
                        },
                        new
                        {
                            Id = 41,
                            ChatId = 16,
                            CreatedAt = new DateTime(2023, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRead = true,
                            UserId = 22,
                            Value = "Corporis excepturi in in et dolore aliquid recusandae inventore."
                        },
                        new
                        {
                            Id = 42,
                            ChatId = 28,
                            CreatedAt = new DateTime(2023, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRead = true,
                            UserId = 21,
                            Value = "Maxime qui incidunt amet voluptatem ut quibusdam."
                        },
                        new
                        {
                            Id = 43,
                            ChatId = 27,
                            CreatedAt = new DateTime(2023, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRead = true,
                            UserId = 29,
                            Value = "Mollitia expedita et ut id dolor labore qui."
                        },
                        new
                        {
                            Id = 44,
                            ChatId = 29,
                            CreatedAt = new DateTime(2023, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRead = true,
                            UserId = 40,
                            Value = "Harum recusandae asperiores repudiandae dolor beatae ea."
                        },
                        new
                        {
                            Id = 45,
                            ChatId = 32,
                            CreatedAt = new DateTime(2023, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRead = true,
                            UserId = 14,
                            Value = "Ipsum aspernatur cupiditate minus quibusdam et voluptatem."
                        },
                        new
                        {
                            Id = 46,
                            ChatId = 15,
                            CreatedAt = new DateTime(2023, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRead = true,
                            UserId = 14,
                            Value = "Quidem dicta officia sint et."
                        },
                        new
                        {
                            Id = 47,
                            ChatId = 10,
                            CreatedAt = new DateTime(2023, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRead = true,
                            UserId = 36,
                            Value = "Similique eligendi rem vel qui rerum aut."
                        },
                        new
                        {
                            Id = 48,
                            ChatId = 18,
                            CreatedAt = new DateTime(2023, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRead = true,
                            UserId = 5,
                            Value = "Deleniti sequi iusto excepturi aut."
                        },
                        new
                        {
                            Id = 49,
                            ChatId = 39,
                            CreatedAt = new DateTime(2023, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRead = true,
                            UserId = 14,
                            Value = "Quisquam provident earum magni aut labore itaque."
                        },
                        new
                        {
                            Id = 50,
                            ChatId = 6,
                            CreatedAt = new DateTime(2023, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRead = true,
                            UserId = 1,
                            Value = "Ut architecto asperiores ducimus qui pariatur nihil."
                        });
                });

            modelBuilder.Entity("ChatApp.DAL.Entities.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Expires")
                        .HasColumnType("datetime2");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("ChatApp.DAL.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2023, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Junior14@hotmail.com",
                            Password = "lwhrmF3n3U/fUvJJxw9a7sfr5bdtbshOyPj0cDq1XgA=",
                            Salt = "SkApdc90bA/0vsJNHgTrS7WY/qhGtWohhkaC/hDkhBo=",
                            UserName = "Erwin_Jenkins"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2023, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Monique_Schneider@gmail.com",
                            Password = "lpsUbsg6Ci7+VxIvDOW60ppdnaJKjJM3TJLJIk92+Ak=",
                            Salt = "SkApdc90bA/0vsJNHgTrS7WY/qhGtWohhkaC/hDkhBo=",
                            UserName = "Taya73"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2023, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Trever_Ledner10@gmail.com",
                            Password = "rsJDVz7aubJOC7krUyp08x609xi5QsysXvVWA5apuxU=",
                            Salt = "SkApdc90bA/0vsJNHgTrS7WY/qhGtWohhkaC/hDkhBo=",
                            UserName = "Hazle36"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2023, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Treva_Abernathy@yahoo.com",
                            Password = "1Ga/eMKkkJ40K6cjt6bewT2XjRDMdbJqHK/2QQn0Mm0=",
                            Salt = "SkApdc90bA/0vsJNHgTrS7WY/qhGtWohhkaC/hDkhBo=",
                            UserName = "Anastasia.Kuhlman"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2023, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Dino17@gmail.com",
                            Password = "Hg5krs87MCNHoK32vJs+IrvgBbvQh/YA7JUalNJAvRI=",
                            Salt = "SkApdc90bA/0vsJNHgTrS7WY/qhGtWohhkaC/hDkhBo=",
                            UserName = "Coty_Bergnaum"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2023, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Monserrate_Kuhlman88@gmail.com",
                            Password = "qBucaiT+vGl6P9LKTuDtvprEU0gLQgkYr6PYl3EylyQ=",
                            Salt = "SkApdc90bA/0vsJNHgTrS7WY/qhGtWohhkaC/hDkhBo=",
                            UserName = "Jamar72"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2023, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Conor23@yahoo.com",
                            Password = "zuMYd8t2ZrxkOzUxyws8Y1PIXCQFN47VG5/9daiHRAQ=",
                            Salt = "SkApdc90bA/0vsJNHgTrS7WY/qhGtWohhkaC/hDkhBo=",
                            UserName = "Austin_Johnson"
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2023, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Mauricio.Padberg68@hotmail.com",
                            Password = "MgkcgqQrhUnjBCB2gyK1pslZni+2w8E+xUywWirVsig=",
                            Salt = "SkApdc90bA/0vsJNHgTrS7WY/qhGtWohhkaC/hDkhBo=",
                            UserName = "Johnathan62"
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2023, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Vada61@hotmail.com",
                            Password = "/1tPphLylBea7qQt+tDtKl5Ow/OlreKCape08/KrzA4=",
                            Salt = "SkApdc90bA/0vsJNHgTrS7WY/qhGtWohhkaC/hDkhBo=",
                            UserName = "Karianne.Durgan11"
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2023, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Darien66@gmail.com",
                            Password = "FBUugg+qfqkV92bg54WxEY5JdXCjdtTQ2YKSi02AGRs=",
                            Salt = "SkApdc90bA/0vsJNHgTrS7WY/qhGtWohhkaC/hDkhBo=",
                            UserName = "Steve_Jacobi51"
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2023, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Danika.Satterfield@yahoo.com",
                            Password = "Bqmmi9fvp5Z/KIEJd48J7+fz4W1YQPRBVyGYxi7R5nM=",
                            Salt = "SkApdc90bA/0vsJNHgTrS7WY/qhGtWohhkaC/hDkhBo=",
                            UserName = "Orlo.Rau"
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2023, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Damion_Moen25@hotmail.com",
                            Password = "9lDl5FCEIrmuACTTqzk8GSna2BHyoRSV4g5JzWV/hX0=",
                            Salt = "SkApdc90bA/0vsJNHgTrS7WY/qhGtWohhkaC/hDkhBo=",
                            UserName = "Tad.Mills"
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2023, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Lazaro.Wehner@hotmail.com",
                            Password = "zycTTgIW/N6APTYA9sdtXIlIIfB3zghPnDd/xU65y6s=",
                            Salt = "SkApdc90bA/0vsJNHgTrS7WY/qhGtWohhkaC/hDkhBo=",
                            UserName = "Doug.Legros"
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2023, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Andrew.Lueilwitz@yahoo.com",
                            Password = "uVYBkf0C29WNiHCN296jDhJmF2ezc8pNEz4J6zDX2uQ=",
                            Salt = "SkApdc90bA/0vsJNHgTrS7WY/qhGtWohhkaC/hDkhBo=",
                            UserName = "Danny.Mayert49"
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2023, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Dejuan_Blick@hotmail.com",
                            Password = "lewDb/3SjyKKLZF19A2AeR7Pczvts0Lk2e845xHlMD8=",
                            Salt = "SkApdc90bA/0vsJNHgTrS7WY/qhGtWohhkaC/hDkhBo=",
                            UserName = "Gabriel.Strosin33"
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2023, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Gilda_Shanahan@hotmail.com",
                            Password = "TPYMfKxODH/gWV+7GBpysc7ImYj0FAz9WeG9US4YgBI=",
                            Salt = "SkApdc90bA/0vsJNHgTrS7WY/qhGtWohhkaC/hDkhBo=",
                            UserName = "Triston.Doyle"
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2023, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Bonnie80@yahoo.com",
                            Password = "hiPKuQgjsxOlE5jKR/xY/93/mNTA8zWylZ8Bfo4/Jrk=",
                            Salt = "SkApdc90bA/0vsJNHgTrS7WY/qhGtWohhkaC/hDkhBo=",
                            UserName = "Whitney_Ankunding"
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2023, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Mariah63@yahoo.com",
                            Password = "dCKmR/6d/ISB+Tq8hQ8P9R8Pz+MyHsZZrISeRuRkOF0=",
                            Salt = "SkApdc90bA/0vsJNHgTrS7WY/qhGtWohhkaC/hDkhBo=",
                            UserName = "Dylan.Ryan8"
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2023, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Darren_Halvorson@gmail.com",
                            Password = "hkuqWbjFa53SPlzbzt+yO0VykC9Jc1ptBKvHWwCAmBg=",
                            Salt = "SkApdc90bA/0vsJNHgTrS7WY/qhGtWohhkaC/hDkhBo=",
                            UserName = "Kiana4"
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2023, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Jerad_Will52@hotmail.com",
                            Password = "X2uda1noU0bTQgJ0wobC3PLnrXgZtEbMKGxj6uQ5Eeo=",
                            Salt = "SkApdc90bA/0vsJNHgTrS7WY/qhGtWohhkaC/hDkhBo=",
                            UserName = "Sienna_Hahn"
                        },
                        new
                        {
                            Id = 21,
                            CreatedAt = new DateTime(2023, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Friedrich.Padberg@gmail.com",
                            Password = "wQDOsyXUyLpe03u58+PCYGQfc8faE9ygrJpS04FwbrU=",
                            Salt = "SkApdc90bA/0vsJNHgTrS7WY/qhGtWohhkaC/hDkhBo=",
                            UserName = "Brionna_Hilll11"
                        },
                        new
                        {
                            Id = 22,
                            CreatedAt = new DateTime(2023, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Lulu_Ondricka41@gmail.com",
                            Password = "boYmn9iuSl0KRxjDAyPLNB2KVAyLlQYmTjTs9gYuJcI=",
                            Salt = "SkApdc90bA/0vsJNHgTrS7WY/qhGtWohhkaC/hDkhBo=",
                            UserName = "Aliyah_Bartoletti39"
                        },
                        new
                        {
                            Id = 23,
                            CreatedAt = new DateTime(2023, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Rahsaan82@hotmail.com",
                            Password = "EukefFXMQCk3fCETPL+BXrSBXKHAtFDOCXLumkeKnGc=",
                            Salt = "SkApdc90bA/0vsJNHgTrS7WY/qhGtWohhkaC/hDkhBo=",
                            UserName = "Madyson.Hessel"
                        },
                        new
                        {
                            Id = 24,
                            CreatedAt = new DateTime(2023, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Ali_Swaniawski@gmail.com",
                            Password = "njjoPY0EbGrfPS+OrD4jzXrXYeDvfH88bgGR9l0tsmo=",
                            Salt = "SkApdc90bA/0vsJNHgTrS7WY/qhGtWohhkaC/hDkhBo=",
                            UserName = "Theresa.Hagenes"
                        },
                        new
                        {
                            Id = 25,
                            CreatedAt = new DateTime(2023, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Marilie_Cassin78@hotmail.com",
                            Password = "S1JDoPkbXeT4tFCFWZKvUUL+opmaLaSzvDTuaaOHcUs=",
                            Salt = "SkApdc90bA/0vsJNHgTrS7WY/qhGtWohhkaC/hDkhBo=",
                            UserName = "Stephanie.Runolfsdottir"
                        },
                        new
                        {
                            Id = 26,
                            CreatedAt = new DateTime(2023, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Frieda.Lebsack@hotmail.com",
                            Password = "g52W+mkjpOWBWH3lU0doJz9lYTyzDIeIJkpHqyqwAiM=",
                            Salt = "SkApdc90bA/0vsJNHgTrS7WY/qhGtWohhkaC/hDkhBo=",
                            UserName = "Margie.DuBuque"
                        },
                        new
                        {
                            Id = 27,
                            CreatedAt = new DateTime(2023, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Reyna.Koelpin74@gmail.com",
                            Password = "MLiUnYLGqNH/7gddVrBFg/jMNIAPFYdsaZ+BfcjXkPU=",
                            Salt = "SkApdc90bA/0vsJNHgTrS7WY/qhGtWohhkaC/hDkhBo=",
                            UserName = "Adam92"
                        },
                        new
                        {
                            Id = 28,
                            CreatedAt = new DateTime(2023, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Jordon49@yahoo.com",
                            Password = "fznVrLr46z4LziQPnk/VYb4HHQn/3bzwdhn49nMtvF0=",
                            Salt = "SkApdc90bA/0vsJNHgTrS7WY/qhGtWohhkaC/hDkhBo=",
                            UserName = "Henri_Jacobson6"
                        },
                        new
                        {
                            Id = 29,
                            CreatedAt = new DateTime(2023, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Muhammad.Gottlieb@gmail.com",
                            Password = "oWkat6NPwyY2ql8WVt2LgfHpYb5HQ/IMxvpHXa5WUyI=",
                            Salt = "SkApdc90bA/0vsJNHgTrS7WY/qhGtWohhkaC/hDkhBo=",
                            UserName = "Eldred_West"
                        },
                        new
                        {
                            Id = 30,
                            CreatedAt = new DateTime(2023, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Sandrine87@yahoo.com",
                            Password = "62XuR9XDe2JbQ0vFZHbJaU7dA/zgaVbODz0WxHVBh0U=",
                            Salt = "SkApdc90bA/0vsJNHgTrS7WY/qhGtWohhkaC/hDkhBo=",
                            UserName = "Carmel.Gaylord"
                        },
                        new
                        {
                            Id = 31,
                            CreatedAt = new DateTime(2023, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Jodie78@hotmail.com",
                            Password = "G4PInBM9ZuogJJUhkI1WNerweSf3H0k676Vb9wsAkvQ=",
                            Salt = "SkApdc90bA/0vsJNHgTrS7WY/qhGtWohhkaC/hDkhBo=",
                            UserName = "Lou46"
                        },
                        new
                        {
                            Id = 32,
                            CreatedAt = new DateTime(2023, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Dino22@yahoo.com",
                            Password = "T9RDnMJzS95wUbhOZouh3rK/kZ8kqhJAdqWIAK2xMSg=",
                            Salt = "SkApdc90bA/0vsJNHgTrS7WY/qhGtWohhkaC/hDkhBo=",
                            UserName = "Linwood25"
                        },
                        new
                        {
                            Id = 33,
                            CreatedAt = new DateTime(2023, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Anita23@gmail.com",
                            Password = "WgpgS2KgToBclpdQkUjjWeHuChbZd/3vint87LmXu3s=",
                            Salt = "SkApdc90bA/0vsJNHgTrS7WY/qhGtWohhkaC/hDkhBo=",
                            UserName = "Lavonne.Konopelski"
                        },
                        new
                        {
                            Id = 34,
                            CreatedAt = new DateTime(2023, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Selmer45@hotmail.com",
                            Password = "4m137u/irqn7ip4B9qtAjS8IpZMNRwqQsVFM8RKaipM=",
                            Salt = "SkApdc90bA/0vsJNHgTrS7WY/qhGtWohhkaC/hDkhBo=",
                            UserName = "Rod.Smitham"
                        },
                        new
                        {
                            Id = 35,
                            CreatedAt = new DateTime(2023, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Kory_Rodriguez@hotmail.com",
                            Password = "kcIeST+0Pr4UryL23GzBjKibKJNqiVwnk0ycsYblyJQ=",
                            Salt = "SkApdc90bA/0vsJNHgTrS7WY/qhGtWohhkaC/hDkhBo=",
                            UserName = "Cecile89"
                        },
                        new
                        {
                            Id = 36,
                            CreatedAt = new DateTime(2023, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Estefania96@gmail.com",
                            Password = "g2NmtOMTg0VCQacC08YMvcZg54z2/wFgkQzm/sbUwQc=",
                            Salt = "SkApdc90bA/0vsJNHgTrS7WY/qhGtWohhkaC/hDkhBo=",
                            UserName = "Doug_Buckridge88"
                        },
                        new
                        {
                            Id = 37,
                            CreatedAt = new DateTime(2023, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Jalyn_Goldner@yahoo.com",
                            Password = "StimVdskm+C3I+GkDdFTHOueI7cK4itL9RqyFSnt61U=",
                            Salt = "SkApdc90bA/0vsJNHgTrS7WY/qhGtWohhkaC/hDkhBo=",
                            UserName = "Rahul.Mitchell68"
                        },
                        new
                        {
                            Id = 38,
                            CreatedAt = new DateTime(2023, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Jaunita_Hintz@hotmail.com",
                            Password = "Fvdq2ECdAp0mpPOtZe5Jb6bjKnpMHZQKhd1HO4Fb1R8=",
                            Salt = "SkApdc90bA/0vsJNHgTrS7WY/qhGtWohhkaC/hDkhBo=",
                            UserName = "Garry.Goodwin14"
                        },
                        new
                        {
                            Id = 39,
                            CreatedAt = new DateTime(2023, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Renee_Medhurst85@gmail.com",
                            Password = "5bYTW7Ds9DJ+xGafWph+gcQWbpBTndBawve2OUOz6sU=",
                            Salt = "SkApdc90bA/0vsJNHgTrS7WY/qhGtWohhkaC/hDkhBo=",
                            UserName = "Roosevelt.Dooley22"
                        },
                        new
                        {
                            Id = 40,
                            CreatedAt = new DateTime(2023, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Waylon_Jones39@hotmail.com",
                            Password = "yCDFlCim+uOfnnCtimrCX4G3lkOmWhfiS8m4yr5BgvE=",
                            Salt = "SkApdc90bA/0vsJNHgTrS7WY/qhGtWohhkaC/hDkhBo=",
                            UserName = "Deven13"
                        });
                });

            modelBuilder.Entity("ChatApp.DAL.Entities.UserChats", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("ChatId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "ChatId");

                    b.HasIndex("ChatId");

                    b.ToTable("UserChats");

                    b.HasData(
                        new
                        {
                            UserId = 37,
                            ChatId = 4
                        },
                        new
                        {
                            UserId = 28,
                            ChatId = 4
                        },
                        new
                        {
                            UserId = 15,
                            ChatId = 8
                        },
                        new
                        {
                            UserId = 22,
                            ChatId = 8
                        },
                        new
                        {
                            UserId = 7,
                            ChatId = 30
                        },
                        new
                        {
                            UserId = 34,
                            ChatId = 30
                        });
                });

            modelBuilder.Entity("ChatApp.DAL.Entities.Message", b =>
                {
                    b.HasOne("ChatApp.DAL.Entities.Chat", "Chat")
                        .WithMany("Messages")
                        .HasForeignKey("ChatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ChatApp.DAL.Entities.User", "User")
                        .WithMany("Messages")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chat");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ChatApp.DAL.Entities.RefreshToken", b =>
                {
                    b.HasOne("ChatApp.DAL.Entities.User", "User")
                        .WithOne()
                        .HasForeignKey("ChatApp.DAL.Entities.RefreshToken", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ChatApp.DAL.Entities.UserChats", b =>
                {
                    b.HasOne("ChatApp.DAL.Entities.Chat", "Chat")
                        .WithMany("UserChats")
                        .HasForeignKey("ChatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ChatApp.DAL.Entities.User", "User")
                        .WithMany("UserChats")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chat");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ChatApp.DAL.Entities.Chat", b =>
                {
                    b.Navigation("Messages");

                    b.Navigation("UserChats");
                });

            modelBuilder.Entity("ChatApp.DAL.Entities.User", b =>
                {
                    b.Navigation("Messages");

                    b.Navigation("UserChats");
                });
#pragma warning restore 612, 618
        }
    }
}
